const $=id=>document.getElementById(id);
const state={running:false,stream:null,language:'en-IN',lastSpeak:0,model:null,modelReady:false,detector:null,stable:0,lastLabel:null,evidence:0,webConfig:null};
const phrases={en:{ready:"I’m ready. I’ll inspect the scene and collect evidence automatically.",scan:"I’m analyzing the scene now.",done:o=>`I’ve identified ${o}. I combined multiple observations.`,unknown:"I don’t have enough evidence yet. I’ll keep looking.",guide:t=>t},hi:{ready:"मैं तैयार हूँ। मैं दृश्य को समझकर अपने आप प्रमाण एकत्र करूँगा।",scan:"मैं अभी दृश्य का विश्लेषण कर रहा हूँ।",done:o=>`मैंने ${o} पहचाना है। मैंने कई प्रमाण मिलाए हैं।`,unknown:"अभी पर्याप्त प्रमाण नहीं हैं। मैं और जाँच करूँगा।",guide:t=>t},te:{ready:"నేను సిద్ధంగా ఉన్నాను. దృశ్యాన్ని అర్థం చేసుకుని ఆధారాలను సేకరిస్తాను.",scan:"నేను ఇప్పుడు దృశ్యాన్ని విశ్లేషిస్తున్నాను.",done:o=>`నేను ${o}ని గుర్తించాను. అనేక ఆధారాలను కలిపాను.`,unknown:"ఇంకా సరిపడా ఆధారాలు లేవు. నేను మరింత పరిశీలిస్తాను.",guide:t=>t},ta:{ready:"நான் தயாராக இருக்கிறேன். காட்சியைப் புரிந்து ஆதாரங்களைச் சேகரிப்பேன்.",scan:"நான் இப்போது காட்சியை ஆய்வு செய்கிறேன்.",done:o=>`நான் ${o} என்பதை அடையாளம் கண்டேன். பல ஆதாரங்களை இணைத்தேன்.`,unknown:"இன்னும் போதுமான ஆதாரம் இல்லை. தொடர்ந்து ஆய்வு செய்கிறேன்.",guide:t=>t},gu:{ready:"હું તૈયાર છું. હું દૃશ્યને સમજીને આપમેળે પુરાવા એકત્ર કરીશ.",scan:"હું હવે દૃશ્યનું વિશ્લેષણ કરી રહ્યો છું.",done:o=>`મેં ${o} ઓળખ્યું છે. મેં ઘણા પુરાવા જોડ્યા છે.`,unknown:"હજુ પૂરતા પુરાવા નથી. હું વધુ તપાસ કરીશ.",guide:t=>t}};
function speak(t){if(!window.speechSynthesis)return;const u=new SpeechSynthesisUtterance(t);u.lang=state.language;u.rate=.94;window.speechSynthesis.cancel();window.speechSynthesis.speak(u)}
function say(k,a){const p=phrases[state.language.slice(0,2)]||phrases.en,t=typeof p[k]==='function'?p[k](a):p[k];$('conversation').textContent=t;if(Date.now()-state.lastSpeak>2200){state.lastSpeak=Date.now();speak(t)}}
function analyseFrame(){const v=$('camera'),c=document.createElement('canvas');c.width=160;c.height=100;const x=c.getContext('2d');x.drawImage(v,0,0,160,100);const d=x.getImageData(0,0,160,100).data;let s=0,dark=0,bright=0;for(let i=0;i<d.length;i+=4){const z=(d[i]+d[i+1]+d[i+2])/3;s+=z;if(z<25)dark++;if(z>245)bright++}const n=d.length/4,m=s/n;const lighting=m<55||dark/n>.3?'low light':m>220||bright/n>.18?'overexposed':'balanced';$('lighting').textContent='LIGHTING — '+lighting;$('lightValue').textContent=lighting;return lighting}
function feature(){const cfg=state.webConfig,n=cfg.image_size,v=$('camera'),vw=v.videoWidth||1280,vh=v.videoHeight||720,rw=vw*cfg.roi.width_ratio,rh=vh*cfg.roi.height_ratio,c=document.createElement('canvas');c.width=n;c.height=n;const ctx=c.getContext('2d');ctx.drawImage(v,(vw-rw)/2,(vh-rh)/2,rw,rh,0,0,n,n);const rgb=ctx.getImageData(0,0,n,n).data,h=new Float32Array(288),gray=new Float32Array(n*n);function hsvBgr(b,g,r){const mx=Math.max(r,g,b),mn=Math.min(r,g,b),delta=mx-mn;let hh=0;if(delta){if(mx===r)hh=((g-b)/delta)%6;else if(mx===g)hh=(b-r)/delta+2;else hh=(r-g)/delta+4;hh*=30;if(hh<0)hh+=180}const s=mx?delta/mx:0;return[hh,s*255,mx]}for(let y=0;y<n;y++)for(let x=0;x<n;x++){const i=(y*n+x)*4;const [hh,ss,vv]=hsvBgr(rgb[i+2],rgb[i+1],rgb[i]);h[Math.min(11,Math.floor(hh/15))*24+Math.min(5,Math.floor(ss/256*6))*4+Math.min(3,Math.floor(vv/256*4))]++;gray[y*n+x]=(0.114*rgb[i]+0.587*rgb[i+1]+0.299*rgb[i+2])}let hs=h.reduce((a,b)=>a+b,0);for(let i=0;i<h.length;i++)h[i]/=hs+1e-8;const gh=new Float32Array(9),kx=[-1,0,1,-2,0,2,-1,0,1],ky=[-1,-2,-1,0,0,0,1,2,1];for(let y=1;y<n-1;y++)for(let x=1;x<n-1;x++){let gx=0,gy=0,k=0;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++,k++){const z=gray[(y+dy)*n+x+dx];gx+=z*kx[k];gy+=z*ky[k]}let a=Math.atan2(gy,gx)*180/Math.PI;if(a<0)a+=360;gh[Math.min(8,Math.floor(a/40))]+=Math.hypot(gx,gy)}let gs=gh.reduce((a,b)=>a+b,0);for(let i=0;i<9;i++)gh[i]/=gs+1e-8;const sm=document.createElement('canvas');sm.width=32;sm.height=32;sm.getContext('2d').drawImage(c,0,0,32,32);const sd=sm.getContext('2d').getImageData(0,0,32,32).data,tx=[];for(let y=0;y<32;y+=8)for(let x=0;x<32;x+=8){let m=0,m2=0;for(let dy=0;dy<8;dy++)for(let dx=0;dx<8;dx++){const i=((y+dy)*32+x+dx)*4,z=(.114*sd[i]+.587*sd[i+1]+.299*sd[i+2])/255;m+=z;m2+=z*z}m/=64;tx.push(m,Math.sqrt(Math.max(0,m2/64-m*m)))}return Float32Array.from([...h,...gh,...tx])}
async function loadModel(){state.webConfig=await fetch('model_config.json').then(r=>r.json());state.model=await fetch('model.json').then(r=>r.json());if(state.model.feature_length!==329)throw Error('feature contract mismatch');state.modelReady=true;$('eval').textContent='Browser inference: trained model active'}
function predict(f){const m=state.model,z=[];for(let k=0;k<m.labels.length;k++){let s=m.b[k];for(let j=0;j<f.length;j++)s+=(f[j]-m.mean[j])/Math.max(m.std[j],1e-8)*m.W[j][k];z.push(s/Math.max(m.temperature,1e-3))}const mx=Math.max(...z),e=z.map(v=>Math.exp(v-mx)),sum=e.reduce((a,b)=>a+b,0),p=e.map(v=>v/sum),o=p.map((v,i)=>[v,i]).sort((a,b)=>b[0]-a[0]);return{label:m.labels[o[0][1]],confidence:o[0][0],margin:o[0][0]-o[1][0]}}
function colour(){const c=document.createElement('canvas');c.width=64;c.height=64;c.getContext('2d').drawImage($('camera'),0,0,64,64);const d=c.getContext('2d').getImageData(0,0,64,64).data;let r=0,g=0,b=0,n=0;for(let i=0;i<d.length;i+=16){r+=d[i];g+=d[i+1];b+=d[i+2];n++}r/=n;g/=n;b/=n;const mx=Math.max(r,g,b),mn=Math.min(r,g,b);return mx-mn<28?(mx<70?'black':mx>190?'white':'silver/grey'):g>r*1.15&&g>b*1.1?'green':b>r*1.2?'blue':r>g*1.25?'red':'neutral'}
function progress(p){if(state.lastLabel===p.label)state.stable++;else{state.lastLabel=p.label;state.stable=1}state.evidence=Math.min(7,state.stable);$('evidenceBar').style.width=(state.evidence/7*100)+'%';$('evidenceText').textContent=state.evidence+' / 7 consistent observations'}
async function process(){if(!state.running)return;const lighting=analyseFrame();let det=[];if(state.detector)try{det=await state.detector.detect($('camera'))}catch(e){}const person=det.find(x=>x.class==='person'&&x.score>.6);if(person){state.stable=0;state.lastLabel=null;$('systemStatus').textContent='PERSON DETECTED';say('guide','Please move your hand or body away from the object.')}else if(state.modelReady){const p=predict(feature());const threshold=Math.max(state.webConfig.confidence_threshold,state.model.unknown_threshold);if(p.confidence>=threshold&&p.margin>=state.webConfig.margin_threshold){progress(p);$('object').textContent=p.label.replaceAll('_',' ');$('confidence').textContent=Math.round(p.confidence*100)+'%';$('colour').textContent=colour();$('systemStatus').textContent=state.evidence>=7?'VERIFIED':'COLLECTING';if(state.evidence===7)say('done',p.label.replaceAll('_',' '))}else{state.stable=0;state.lastLabel=null;$('systemStatus').textContent='UNCERTAIN';say('unknown')}}else{$('systemStatus').textContent='MODEL UNAVAILABLE'}$('conditionText').textContent=lighting;requestAnimationFrame(process)}
async function start(){if(state.running)return;try{state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30}},audio:false});$('camera').srcObject=state.stream;state.running=true;$('systemStatus').textContent='PERCEIVING';say('scan');await loadModel();try{state.detector=await cocoSsd.load()}catch(e){}process()}catch(e){$('systemStatus').textContent='CAMERA UNAVAILABLE';$('eval').textContent=e.message;say('unknown')}}
function reset(){state.stable=0;state.lastLabel=null;state.evidence=0;$('evidenceBar').style.width='0';$('evidenceText').textContent='0 / 7 consistent observations';['object','colour','confidence'].forEach(id=>$(id).textContent='—');$('systemStatus').textContent=state.running?'PERCEIVING':'READY';say('ready')}
$('start').onclick=start;$('capture').onclick=()=>{if(state.running)say('scan');else say('ready')};$('reset').onclick=reset;$('language').onchange=e=>{state.language=e.target.value;say('ready')};say('ready');
