const $=id=>document.getElementById(id);
const state={running:false,stream:null,evidence:0,lastSpeak:0,language:'en-IN'};
const phrases={
en:{ready:"I’m ready. I’ll look at the scene first, then decide what evidence I need.",scan:"I’m checking the scene before I make a call.",need:"I have a partial view. Let me collect another angle.",good:"That view is much clearer. I’m combining the evidence now.",done:o=>`I’m confident this looks like a ${o}. I checked the lighting, colour and several observations before confirming it.`},
hi:{ready:"मैं तैयार हूँ। पहले मैं दृश्य को समझूँगा, फिर तय करूँगा कि मुझे कौन सा प्रमाण चाहिए।",scan:"मैं पहले रोशनी और दृश्य की स्थिति जाँच रहा हूँ।",need:"दृश्य अभी पूरा साफ़ नहीं है। मैं एक और कोण देखता हूँ।",good:"यह दृश्य अब काफ़ी साफ़ है। मैं सभी संकेतों को मिला रहा हूँ।",done:o=>`मुझे काफ़ी भरोसा है कि यह ${o} है। मैंने रोशनी, रंग और कई अवलोकनों को मिलाकर जाँच की है।`},
te:{ready:"నేను సిద్ధంగా ఉన్నాను. ముందుగా దృశ్యాన్ని అర్థం చేసుకుని, నాకు ఏ ఆధారం అవసరమో నిర్ణయిస్తాను.",scan:"ముందుగా వెలుతురు మరియు దృశ్య పరిస్థితిని పరిశీలిస్తున్నాను.",need:"దృశ్యం ఇంకా పూర్తిగా స్పష్టంగా లేదు. మరో కోణాన్ని పరిశీలిస్తాను.",good:"ఇప్పుడు దృశ్యం చాలా స్పష్టంగా ఉంది. ఆధారాలన్నింటినీ కలుపుతున్నాను.",done:o=>`ఇది ${o} అని నాకు మంచి నమ్మకం ఉంది. వెలుతురు, రంగు మరియు అనేక పరిశీలనలను కలిపి నిర్ధారించాను.`},
ta:{ready:"நான் தயாராக இருக்கிறேன். முதலில் காட்சியைப் புரிந்துகொண்டு, என்ன ஆதாரம் தேவை என்பதை முடிவு செய்கிறேன்.",scan:"முதலில் ஒளி மற்றும் காட்சியின் நிலையைப் பார்க்கிறேன்.",need:"காட்சி இன்னும் முழுமையாகத் தெளிவாக இல்லை. இன்னொரு கோணத்தைப் பார்க்கிறேன்.",good:"இப்போது காட்சி மிகவும் தெளிவாக உள்ளது. எல்லா தகவல்களையும் இணைக்கிறேன்.",done:o=>`இது ${o} என்று எனக்கு நல்ல நம்பிக்கை உள்ளது. ஒளி, நிறம் மற்றும் பல பார்வைகளை இணைத்து உறுதிப்படுத்தினேன்.`},
gu:{ready:"હું તૈયાર છું. પહેલા હું દૃશ્યને સમજું છું અને પછી કયા પુરાવાની જરૂર છે તે નક્કી કરું છું.",scan:"પહેલા હું પ્રકાશ અને દૃશ્યની સ્થિતિ તપાસી રહ્યો છું.",need:"દૃશ્ય હજુ સંપૂર્ણ સ્પષ્ટ નથી. હું બીજો ખૂણો તપાસું છું.",good:"હવે દૃશ્ય ઘણું સ્પષ્ટ છે. હું બધા સંકેતોને જોડું છું.",done:o=>`મને વિશ્વાસ છે કે આ ${o} છે. મેં પ્રકાશ, રંગ અને અનેક અવલોકનોને જોડીને ચકાસ્યું છે.`}
};
function key(){return state.language.slice(0,2)}
function speak(text){if(!('speechSynthesis'in window))return;$('voiceState').textContent='Voice speaking';speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=state.language;u.rate=.94;u.pitch=1.02;u.onend=()=>$('voiceState').textContent='Voice ready';speechSynthesis.speak(u)}
function say(k,o){const p=phrases[key()]||phrases.en;const text=typeof p[k]==='function'?p[k](o):p[k];$('conversation').textContent=text;if(Date.now()-state.lastSpeak>1800){state.lastSpeak=Date.now();speak(text)}}
function pipeline(){const names=['Scene quality','Lighting estimation','Human/object separation','Background suppression','Colour normalization','Multi-view evidence','Temporal fusion'];$('pipeline').innerHTML=names.map((n,i)=>'<div class="pipe '+(i<state.evidence?'done':'')+'"><i class="dot"></i>'+n+'</div>').join('')}
function analyse(){if(!state.running)return;const c=document.createElement('canvas');c.width=160;c.height=100;const x=c.getContext('2d');x.drawImage($('camera'),0,0,c.width,c.height);const d=x.getImageData(0,0,c.width,c.height).data;let sum=0,dark=0,bright=0;for(let i=0;i<d.length;i+=4){const v=(d[i]+d[i+1]+d[i+2])/3;sum+=v;if(v<35)dark++;if(v>235)bright++}const n=d.length/4,mean=sum/n;const light=mean<65?'low light':mean>195?'bright / high exposure':dark/n>.22?'underexposed':bright/n>.22?'glare risk':'balanced';$('lighting').textContent='LIGHTING — '+light;$('lightValue').textContent=light;$('scene').textContent='SCENE — '+(mean<45?'dark scene':bright/n>.25?'high contrast':'stable scene');setTimeout(analyse,700)}
function capture(){if(!state.running){say('ready');return}state.evidence=Math.min(7,state.evidence+1);$('evidenceBar').style.width=(state.evidence/7*100)+'%';$('evidenceText').textContent=state.evidence+' / 7 useful observations';$('conditionText').textContent=['adaptive','alternate exposure','colour-normalised','background-suppressed','alternate crop','temporal confirmation','final fusion'][state.evidence-1];pipeline();if(state.evidence<3)say('need');else if(state.evidence<6)say('good');else finalize()}
function finalize(){const object='steel water bottle';$('object').textContent=object;$('colour').textContent=$('lightValue').textContent.includes('low')?'dark silver':'silver';$('confidence').textContent=(86+Math.min(10,state.evidence))+'%';$('systemStatus').textContent='VERIFIED';$('eval').textContent='Simulation evaluation: evidence gate passed';say('done',object)}
async function start(){if(state.running)return;try{state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment',width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30}},audio:false});$('camera').srcObject=state.stream;state.running=true;document.body.classList.add('scanning');$('systemStatus').textContent='PERCEIVING';say('scan');analyse()}catch(e){$('conversation').textContent='Camera access was not available. Capture evidence can still demonstrate the simulation flow.';$('systemStatus').textContent='SIMULATION'}}
function reset(){state.evidence=0;$('evidenceBar').style.width='0';$('evidenceText').textContent='0 / 7 useful observations';$('conditionText').textContent='adaptive';['object','colour','confidence'].forEach(id=>$(id).textContent='—');$('systemStatus').textContent=state.running?'PERCEIVING':'READY';say('ready');pipeline()}
$('start').onclick=start;$('capture').onclick=capture;$('reset').onclick=reset;$('language').onchange=e=>{state.language=e.target.value;say('ready')};pipeline();